export const ADD_PRODUCT_TO_CART = 'Cart/ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'Cart/REMOVE_PRODUCT_FROM_CART';
export const ADD_PRODUCTS_TO_CART = 'Cart/ADD_PRODUCTS_TO_CART';
